ALTER TABLE "GatarinaPhotoGalleryConfig"
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "GatarinaPhoto"
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "GatarinaPhotoRequest"
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
